name: Publish Debian Bookworm Testing Systemd

on:
  push:
    branches:
      - "main"
    paths:
      - .github/workflows/publish-bookworm-testing.yml
      - bookworm/testing/systemd/**
  schedule:
    - cron: "0 1 */14 * *"

env:
  REPO: "debian-remote"
  DEBIAN_CODE: "bookworm"

jobs:
  Push-Bookworm-Testing-Systemd:
    # runs-on: ubuntu-latest
    strategy:
      matrix:
        DE: [xfce, mate]
    runs-on: buildjet-8vcpu-ubuntu-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: "${{ env.DEBIAN_CODE }}/testing/systemd"
          file: "${{ env.DEBIAN_CODE }}/testing/systemd/Dockerfile.${{ matrix.DE }}"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO }}:testing-${{ env.DEBIAN_CODE }}-systemd-${{ matrix.DE }}"
            