name: Publish Debian Bookworm Slim with Additions

on:
  push:
    branches:
      - "main"
    paths:
      - .github/workflows/publish-bookworm-slim-additions.yml
      - bookworm/slim/**
      - "!bookworm/slim/Dockerfile.mate"
      - "!bookworm/slim/Dockerfile.xfce"
  schedule:
    - cron: "0 1 */14 * *"

env:
  REPO: "debian-remote"
  DEBIAN_CODE: "bookworm"

jobs:
  Push-Bookworm-Slim-Additions:
    strategy:
      matrix:
        DE: [xfce, mate]
        APP: [firefox-esr, libreoffice, vscode]
    runs-on: buildjet-8vcpu-ubuntu-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Default
        uses: docker/build-push-action@v5
        if: ${{ matrix.DE == 'xfce'}}
        with:
          context: "${{ env.DEBIAN_CODE }}/slim"
          file: "${{ env.DEBIAN_CODE }}/slim/Dockerfile.${{ matrix.DE }}.${{ matrix.APP }}"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO }}:slim-${{ matrix.DE }}-${{ matrix.APP }}"
            "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO }}:${{ env.DEBIAN_CODE }}-slim-${{ matrix.APP }}"
            "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO }}:${{ env.DEBIAN_CODE }}-slim-${{ matrix.DE }}-${{ matrix.APP }}"
      - name: Build and Push Other DE
        uses: docker/build-push-action@v5
        if: ${{ matrix.DE != 'xfce'}}
        with:
          context: "${{ env.DEBIAN_CODE }}/slim"
          file: "${{ env.DEBIAN_CODE }}/slim/Dockerfile.${{ matrix.DE }}.${{ matrix.APP }}"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO }}:slim-${{ matrix.DE }}-${{ matrix.APP }}"
            "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO }}:${{ env.DEBIAN_CODE }}-slim-${{ matrix.DE }}-${{ matrix.APP }}"